### ISSUE TITLE
Really good example.. Thanks.

### ISSUE THREAD

**Issue by kalpeshrajvir-virtueinfo** [blacksonic/angular2-babel-esnext-starter#14]
This is really good example showing the crud using angular2. Thanks..!! This will help me to enhance my knowledge of angular2.

I just wanted to know can these be converted using the typescript/ts and if I start npm start it start working?

**Comment by blacksonic** [comment]
You can start adding types in the Javascript, because they will be stripped by the Babel plugin strip-flow-types. It wont assert for types and check it, only adds autocompletion support in IDEs. secondly it can look identical to the Typescript code without the typings files.
After this adding the Typescript loader to Webpack will enable you to convert it with minimal effort. I can make a branch where it is shown on a module how it can be converted.
But for an only Typescript repo i would recommend [this starter pack](https://github.com/AngularClass/angular2-webpack-starter).

**Comment by kalpeshrajvir-virtueinfo** [comment]
@blacksonic It would be more helpful if you can create a branch for that. Because most of the example are not like your application.

**Comment by blacksonic** [comment]
@kalpeshrajvir-virtueinfo created a separate repository with Typescript where the examples can be ported by copy pasting.
https://github.com/blacksonic/angular2-testing-ground
